SOURCES=\
src/ParticleContainer.cpp\
src/outputWriter/XYZWriter.cpp\
src/outputWriter/VTKWriter.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/Calculation.cpp\
src/FileReader.cpp\
src/Particle.cpp\
src/MolSim.cpp\
src/Plotter.cpp\
