// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#include <xsd/cxx/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#include "input.h"

// input_t
// 

const input_t::base_output_file_type& input_t::
base_output_file () const
{
  return this->base_output_file_.get ();
}

input_t::base_output_file_type& input_t::
base_output_file ()
{
  return this->base_output_file_.get ();
}

void input_t::
base_output_file (const base_output_file_type& x)
{
  this->base_output_file_.set (x);
}

void input_t::
base_output_file (::std::auto_ptr< base_output_file_type > x)
{
  this->base_output_file_.set (x);
}

const input_t::frequency_type& input_t::
frequency () const
{
  return this->frequency_.get ();
}

input_t::frequency_type& input_t::
frequency ()
{
  return this->frequency_.get ();
}

void input_t::
frequency (const frequency_type& x)
{
  this->frequency_.set (x);
}

const input_t::delta_t_type& input_t::
delta_t () const
{
  return this->delta_t_.get ();
}

input_t::delta_t_type& input_t::
delta_t ()
{
  return this->delta_t_.get ();
}

void input_t::
delta_t (const delta_t_type& x)
{
  this->delta_t_.set (x);
}

const input_t::tend_type& input_t::
tend () const
{
  return this->tend_.get ();
}

input_t::tend_type& input_t::
tend ()
{
  return this->tend_.get ();
}

void input_t::
tend (const tend_type& x)
{
  this->tend_.set (x);
}

const input_t::input_file_type& input_t::
input_file () const
{
  return this->input_file_.get ();
}

input_t::input_file_type& input_t::
input_file ()
{
  return this->input_file_.get ();
}

void input_t::
input_file (const input_file_type& x)
{
  this->input_file_.set (x);
}

void input_t::
input_file (::std::auto_ptr< input_file_type > x)
{
  this->input_file_.set (x);
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// input_t
//

input_t::
input_t (const base_output_file_type& base_output_file,
         const frequency_type& frequency,
         const delta_t_type& delta_t,
         const tend_type& tend,
         const input_file_type& input_file)
: ::xml_schema::type (),
  base_output_file_ (base_output_file, this),
  frequency_ (frequency, this),
  delta_t_ (delta_t, this),
  tend_ (tend, this),
  input_file_ (input_file, this)
{
}

input_t::
input_t (const input_t& x,
         ::xml_schema::flags f,
         ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  base_output_file_ (x.base_output_file_, f, this),
  frequency_ (x.frequency_, f, this),
  delta_t_ (x.delta_t_, f, this),
  tend_ (x.tend_, f, this),
  input_file_ (x.input_file_, f, this)
{
}

input_t::
input_t (const ::xercesc::DOMElement& e,
         ::xml_schema::flags f,
         ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  base_output_file_ (this),
  frequency_ (this),
  delta_t_ (this),
  tend_ (this),
  input_file_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false);
    this->parse (p, f);
  }
}

void input_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_elements (); p.next_element ())
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // base_output_file
    //
    if (n.name () == "base_output_file" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< base_output_file_type > r (
        base_output_file_traits::create (i, f, this));

      if (!base_output_file_.present ())
      {
        this->base_output_file_.set (r);
        continue;
      }
    }

    // frequency
    //
    if (n.name () == "frequency" && n.namespace_ ().empty ())
    {
      if (!frequency_.present ())
      {
        this->frequency_.set (frequency_traits::create (i, f, this));
        continue;
      }
    }

    // delta_t
    //
    if (n.name () == "delta_t" && n.namespace_ ().empty ())
    {
      if (!delta_t_.present ())
      {
        this->delta_t_.set (delta_t_traits::create (i, f, this));
        continue;
      }
    }

    // tend
    //
    if (n.name () == "tend" && n.namespace_ ().empty ())
    {
      if (!tend_.present ())
      {
        this->tend_.set (tend_traits::create (i, f, this));
        continue;
      }
    }

    // input_file
    //
    if (n.name () == "input_file" && n.namespace_ ().empty ())
    {
      ::std::auto_ptr< input_file_type > r (
        input_file_traits::create (i, f, this));

      if (!input_file_.present ())
      {
        this->input_file_.set (r);
        continue;
      }
    }

    break;
  }

  if (!base_output_file_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "base_output_file",
      "");
  }

  if (!frequency_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "frequency",
      "");
  }

  if (!delta_t_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "delta_t",
      "");
  }

  if (!tend_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "tend",
      "");
  }

  if (!input_file_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "input_file",
      "");
  }
}

input_t* input_t::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class input_t (*this, f, c);
}

input_t& input_t::
operator= (const input_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->base_output_file_ = x.base_output_file_;
    this->frequency_ = x.frequency_;
    this->delta_t_ = x.delta_t_;
    this->tend_ = x.tend_;
    this->input_file_ = x.input_file_;
  }

  return *this;
}

input_t::
~input_t ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::auto_ptr< ::input_t >
input (const ::std::string& u,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::input_t > r (
    ::input (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::input_t >
input (const ::std::string& u,
       ::xml_schema::error_handler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::input_t > r (
    ::input (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::input_t >
input (const ::std::string& u,
       ::xercesc::DOMErrorHandler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::input_t > r (
    ::input (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::input_t >
input (::std::istream& is,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::input (isrc, f, p);
}

::std::auto_ptr< ::input_t >
input (::std::istream& is,
       ::xml_schema::error_handler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::input (isrc, h, f, p);
}

::std::auto_ptr< ::input_t >
input (::std::istream& is,
       ::xercesc::DOMErrorHandler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::input (isrc, h, f, p);
}

::std::auto_ptr< ::input_t >
input (::std::istream& is,
       const ::std::string& sid,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::input (isrc, f, p);
}

::std::auto_ptr< ::input_t >
input (::std::istream& is,
       const ::std::string& sid,
       ::xml_schema::error_handler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::input (isrc, h, f, p);
}

::std::auto_ptr< ::input_t >
input (::std::istream& is,
       const ::std::string& sid,
       ::xercesc::DOMErrorHandler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::input (isrc, h, f, p);
}

::std::auto_ptr< ::input_t >
input (::xercesc::InputSource& i,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  ::std::auto_ptr< ::input_t > r (
    ::input (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::input_t >
input (::xercesc::InputSource& i,
       ::xml_schema::error_handler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::input_t > r (
    ::input (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::input_t >
input (::xercesc::InputSource& i,
       ::xercesc::DOMErrorHandler& h,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  ::std::auto_ptr< ::input_t > r (
    ::input (
      d, f | ::xml_schema::flags::own_dom, p));

  return r;
}

::std::auto_ptr< ::input_t >
input (const ::xercesc::DOMDocument& d,
       ::xml_schema::flags f,
       const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
      static_cast< ::xercesc::DOMDocument* > (d.cloneNode (true)));

    ::std::auto_ptr< ::input_t > r (
      ::input (
        c, f | ::xml_schema::flags::own_dom, p));

    return r;
  }

  const ::xercesc::DOMElement& e (*d.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "input" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::input_t > r (
      ::xsd::cxx::tree::traits< ::input_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "input",
    "");
}

::std::auto_ptr< ::input_t >
input (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
       ::xml_schema::flags f,
       const ::xml_schema::properties&)
{
  ::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "input" &&
      n.namespace_ () == "")
  {
    ::std::auto_ptr< ::input_t > r (
      ::xsd::cxx::tree::traits< ::input_t, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "input",
    "");
}

// Begin epilogue.
//
//
// End epilogue.

#include <xsd/cxx/post.hxx>



